name = "djm-tech-portfolio"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
cwd = "."

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]

[[build.upload.rules]]
type = "Text"
globs = ["**/*.css"]

[[build.upload.rules]]
type = "Data"
globs = ["**/*.json", "**/*.xml", "**/*.txt"]
